version: "3.9"

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: tradingbot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tradingbot:
    build:
      context: .
    env_file:
      - .env
    command: python3 -m src.main
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - ./:/app

volumes:
  pg_data:
  redis_data:
